app/__init__.py
from flask import Flask
from .api.routes import api
from .site.routes import site
from .authentication.routes import auth
from config import Config

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

from models import db as root_db, login_manager, ma

# Import for Flask-Marshmallow
from flask_marshmallow import Marshmallow

from flask_cors import CORS

from helpers import JSONEncoder

app = Flask(__name__)



app.register_blueprint(api)
app.register_blueprint(site)
app.register_blueprint(auth)

app.config.from_object(Config)

root_db.init_app(app)

migrate = Migrate(app,root_db)

login_manager.init_app(app)
login_manager.login_view = 'signin' # Specify what page to load for NON-AUTHED users

ma.init_app(app)

app.json_encoder = JSONEncoder

CORS(app)

import models

app/api/routes.py
from flask import Blueprint, request, jsonify
from helpers import token_required
from models import JournalEntry, db,User,Habit,JournalEntry,habit_schema,habits_schema, journal_entry_schema, journal_entries_schema

api = Blueprint('api', __name__, url_prefix = '/api')

@api.route('/getdata')
@token_required
def getdata(current_user_token):
    return { 'some': 'value'}


# CREATE HABIT ENDPOINT

@api.route('/habits', methods = ['POST'])
@token_required
def create_habit(current_user_token):
    habit_class = request.json['habit_class']
    smart_goal = request.json['smart_goal']
    habit_date = request.json['habit_date']
    habit_steps = request.json['habit_steps']
    user_token = current_user_token.token

    print(f'BIG TESTER: {current_user_token.token}')

    habit = Habit( habit_class,smart_goal,habit_date, habit_steps, user_token = user_token )

    db.session.add(habit)
    db.session.commit()

    response = habit_schema.dump(habit)
    return jsonify(response)




# RETRIEVE ALL HABITS ENDPOINT
@api.route('/habits', methods = ['GET'])
@token_required
def get_habits(current_user_token):
    owner = current_user_token.token
    habits = Habit.query.filter_by(user_token = owner).all()
    response = habits_schema.dump(habits)
    return jsonify(response)


# RETRIEVE ONE HABIT ENDPOINT
@api.route('/habits/<id>', methods = ['GET'])
@token_required
def get_habit(current_user_token, id):
    owner = current_user_token.token
    if owner == current_user_token.token:
        habit = Habit.query.get(id)
        response = habit_schema.dump(habit)
        return jsonify(response)
    else:
        return jsonify({"message": "Valid Token Required"}),401



# UPDATE HABIT ENDPOINT
@api.route('/habits/<id>', methods = ['PUT'])
@token_required
def update_habit(current_user_token,id):
    habit = Habit.query.get(id) # getting instance of habit

    habit.habit_class = request.json['habit_class']
    habit.smart_goal = request.json['smart_goal']
    habit.habit_date = request.json['habit_date']
    habit.habit_steps = request.json['habit_steps']
    habit.user_token = current_user_token.token

    db.session.commit()
    response = habit_schema.dump(habit)
    return jsonify(response)


# DELETE HABIT ENDPOINT
@api.route('/habits/<id>', methods = ['DELETE'])
@token_required
def delete_habit(current_user_token, id):
    habit = Habit.query.get(id)
    db.session.delete(habit)
    db.session.commit()
    response = habit_schema.dump(habit)
    return jsonify(response)


################################
#         JOURNAL ENTRIES      #
################################

# CREATE JOURNAL ENTRY ENDPOINT





@api.route('/journal', methods = ['POST'])
@token_required
def create_entry(current_user_token):
    title = request.json['title']
    entry = request.json['entry']
    entry_date = request.json['entry_date']
    user_token = current_user_token.token

    print(f'BIG TESTER: {current_user_token.token}')

    entry = JournalEntry( title, entry, entry_date, user_token = user_token )

    db.session.add(entry)
    db.session.commit()

    response = journal_entry_schema.dump(entry)
    return jsonify(response)




# RETRIEVE ALL ENTRIES ENDPOINT
@api.route('/journal', methods = ['GET'])
@token_required
def get_entries(current_user_token):
    owner = current_user_token.token
    entries = JournalEntry.query.filter_by(user_token = owner).all()
    response = habits_schema.dump(entries)
    return jsonify(response)


# RETRIEVE ONE JOURNAL ENTRY ENDPOINT
@api.route('/journal/entry/<id>', methods = ['GET'])
@token_required
def get_entry(current_user_token, id):
    owner = current_user_token.token
    if owner == current_user_token.token:
        entry = JournalEntry.query.get(id)
        response = journal_entry_schema.dump(entry)
        return jsonify(response)
    else:
        return jsonify({"message": "Valid Token Required"}),401



# UPDATE Entry ENDPOINT
@api.route('/journal/entry/<id>', methods = ['POST','PUT'])
@token_required
def update_entry(current_user_token,id):
    entry = JournalEntry.query.get(id) # getting instance of journal entry

    title, user_id, entry, entry_date, id=''
    
    entry.title = request.json['title']
    entry.entry = request.json['entry']
    entry.entry_date = request.json['entry_date']
    entry.user_token = current_user_token.token

    db.session.commit()
    response = journal_entry_schema.dump(entry)
    return jsonify(response)


# DELETE ENTRY ENDPOINT
@api.route('/journal/entry/<id>', methods = ['DELETE'])
@token_required
def delete_entry(current_user_token, id):
    entry = JournalEntry.query.get(id)
    db.session.delete(entry)
    db.session.commit()
    response = journal_entry_schema.dump(entry)
    return jsonify(response)

app/authentication/routes.py
#capital in Blueprint indicates that we are working with a class
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models import User, db, check_password_hash
from forms import UserLoginForm

# Imports for flask login
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth',__name__, template_folder ='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
# get gets data from our database, post means they can post on page; methods work universally
# GET/POST/PUT/DELETE are HTTP verbs that describe what we want to do at a given endpoint (location)
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            user = User(email, password)

            db.session.add(user)
            db.session.commit()


            flash(f'You have successfully created  user account {email}', 'User-created')
    
            return redirect(url_for('site.home'))


    except:
        raise Exception('Invalid Form Data: Please Check your Form')
    return render_template('signup.html', form=form)
    


# have a way to sign in

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in: Via Email/Password', 'auth-success')
                return redirect(url_for('site.home'))
            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signin.html', form=form)

app/site/routes.py
from flask import Blueprint, render_template

"""
    Some arguments are specified when creating the Blueprint object.
    The first argument "site", is the blueprint name, 
    which is used by Flask's routing mechanism

    The second argument, __name__, is the Blueprint's import name
    this is how flask locates the blueprint's resources
"""

site = Blueprint('site',__name__,template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="Description" content="Enter your description here" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
    <link rel="stylesheet" href="../static/css/main.css" />
    <title>Mock Text</title>
  </head>
  <body>
    <!-- NavBar Here -->
    <nav class="ct-nav">
        <div>
    <!-- <p>Mock img</p> -->
        </div>

      <!-- Nav Items -->
      <div>
        <ul id="horizontal-list">
          <a href="">
            <li>Mock Text</li>
          </a>
          <a href=""></a>
            <li>Mock Text</li>
          </a>
          <a href="{{ url_for('site.profile') }}">
            <li>Profile</li>
          </a>
          <!-- User Auth Check for SIgnIn/SignUp Nav Buttons -->
          <a href="">
            <li>Log Out</li>
          </a>
          <a href="{{ url_for('auth.signin') }}">
            <li>Sign In</li>
          </a>
          <a href="{{ url_for('auth.signup') }}">
            <li>Sign Up Free</li>
          </a>
        </ul>
      </div>
    </nav>

    <!-- End of Nav -->
    {% block content %}

    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
  </body>
</html>

app/templates/forms.html
<!-- HTML produced by the Flask Form -->

<form method="POST">
  {{ form.hidden_tag() }}
  <div class="form-group">
    <fieldset id="email-field">
      {{ form.email.label }} {{ form.email(class = 'form-control', placeholder =
      'Place email here ') }}
    </fieldset>

    <fieldset id="pass-field">
      {{ form.password.label }} {{ form.password(class = "form-control",
      placeholder = "Place password here ") }}
    </fieldset>

    <!-- Submit button area -->
    {{ form. submit_button(class = "btn btn-primary btn-block") }}
  </div>
</form>